// Location definitions with rich SEO content
export const locations: Record<string, {
  name: string
  borough: string
  description: string
  buildingTypes: string
  transit: string
  character: string
  challenges: string
}> = {
  'manhattan': { name: 'Manhattan', borough: 'Manhattan', description: 'The most densely packed borough with everything from pre-war co-ops to modern high-rises.', buildingTypes: 'Pre-war co-ops, post-war rentals, modern high-rises, walk-ups, luxury condos', transit: 'Best subway coverage in NYC with multiple lines throughout', character: 'Fast-paced, expensive, convenient - the NYC most people picture', challenges: 'Highest rents, limited parking, strict building rules, competitive market' },
  'brooklyn': { name: 'Brooklyn', borough: 'Brooklyn', description: 'NYC\'s most populous borough with diverse neighborhoods from brownstone Brooklyn to beachfront.', buildingTypes: 'Brownstones, row houses, pre-war apartments, new developments, converted lofts', transit: 'Well-connected to Manhattan via multiple subway lines; varies by neighborhood', character: 'Creative, diverse, neighborhood-focused with strong local identities', challenges: 'Gentrification changing neighborhood character, varying transit access' },
  'queens': { name: 'Queens', borough: 'Queens', description: 'The most diverse urban area in the world, with distinct neighborhood identities and more space.', buildingTypes: 'Single-family homes, garden apartments, co-ops, new high-rise developments', transit: 'Limited subway coverage; buses and LIRR supplement. Better near subway lines.', character: 'Residential, diverse, more space for the money, strong ethnic enclaves', challenges: 'Transit deserts away from subway, longer commutes to Manhattan' },
  'bronx': { name: 'The Bronx', borough: 'Bronx', description: 'Often overlooked but offering value, culture, and improving conditions.', buildingTypes: 'Pre-war apartments, public housing, single-family homes, new developments', transit: '4/5/6 and B/D trains serve main corridors; limited in some areas', character: 'Rich history, strong communities, undergoing revitalization', challenges: 'Some areas with higher crime, varying building quality' },
  'staten-island': { name: 'Staten Island', borough: 'Staten Island', description: 'The most suburban borough, feeling like a different world from the rest of NYC.', buildingTypes: 'Single-family homes, townhouses, small apartment buildings', transit: 'Ferry to Manhattan (free), limited bus service, car-dependent', character: 'Suburban feel, more space, waterfront views, slower pace', challenges: 'Long commute without a car, limited nightlife and dining' },
  'upper-east-side': { name: 'Upper East Side', borough: 'Manhattan', description: 'One of Manhattan\'s most established residential neighborhoods, home to Museum Mile.', buildingTypes: 'Pre-war co-ops, luxury condos, townhouses, some walk-ups in Yorkville', transit: '4/5/6 trains (Lexington Ave), Q train (Second Ave), M15 bus', character: 'Refined, quiet residential streets, upscale shopping, museum culture', challenges: 'Very strict co-op boards, expensive, limited nightlife, formal atmosphere' },
  'upper-west-side': { name: 'Upper West Side', borough: 'Manhattan', description: 'A residential neighborhood with cultural institutions and Central Park access.', buildingTypes: 'Pre-war co-ops, brownstones, post-war rentals, luxury towers', transit: '1/2/3 trains (Broadway), B/C trains (Central Park West)', character: 'Family-friendly, intellectual, cultural institutions, tree-lined streets', challenges: 'Competitive for families, strict co-op boards, expensive' },
  'midtown': { name: 'Midtown', borough: 'Manhattan', description: 'The commercial heart of NYC - more office towers than residential, but options exist.', buildingTypes: 'High-rise rentals, some older apartments, hotel conversions', transit: 'Most connected area in NYC - nearly every subway line passes through', character: 'Commercial, bustling, tourist-heavy, convenient for work', challenges: 'Noisy, crowded, fewer neighborhood amenities, expensive' },
  'chelsea': { name: 'Chelsea', borough: 'Manhattan', description: 'Art galleries, the High Line, and a mix of old and new residential buildings.', buildingTypes: 'Pre-war walk-ups, converted lofts, modern high-rises, brownstones', transit: 'A/C/E (8th Ave), 1 train (7th Ave), L train (14th St)', character: 'Creative, LGBTQ-friendly, art galleries, upscale dining', challenges: 'Expensive, limited subway options on west side, nightlife noise' },
  'east-village': { name: 'East Village', borough: 'Manhattan', description: 'Historic neighborhood known for its counterculture history and eclectic character.', buildingTypes: 'Pre-war tenements, walk-ups, some newer developments', transit: 'L train (1st Ave), 6 train (Astor Place), F train (2nd Ave)', character: 'Young, artsy, great food scene, nightlife, punk rock history', challenges: 'Noisy at night, small apartments, walk-ups everywhere, expensive' },
  'west-village': { name: 'West Village', borough: 'Manhattan', description: 'Charming tree-lined streets, historic townhouses, and a coveted residential feel.', buildingTypes: 'Townhouses, brownstones, pre-war walk-ups, some luxury new builds', transit: '1/2/3 (7th Ave), A/C/E/B/D/F/M (various)', character: 'Charming, quiet for Manhattan, excellent restaurants, cobblestone streets', challenges: 'Extremely expensive, confusing street grid, competitive market' },
  'soho': { name: 'SoHo', borough: 'Manhattan', description: 'Former industrial district now known for cast-iron architecture and upscale shopping.', buildingTypes: 'Cast-iron lofts, converted warehouses, some newer luxury', transit: 'N/R/W (Prince St), 6 (Spring St), A/C/E (Spring St)', character: 'High-end shopping, art galleries, Instagram-famous streets', challenges: 'Very expensive, crowded with tourists, limited grocery/residential services' },
  'tribeca': { name: 'Tribeca', borough: 'Manhattan', description: 'Once industrial, now one of NYC\'s most expensive and family-friendly neighborhoods.', buildingTypes: 'Converted lofts, luxury condos, cast-iron buildings', transit: '1/2/3 (Chambers), A/C (Chambers), R/W (City Hall area)', character: 'Wealthy, family-friendly, celebrity sightings, excellent restaurants', challenges: 'Extremely expensive, can feel empty on weekends, limited subway options' },
  'lower-east-side': { name: 'Lower East Side', borough: 'Manhattan', description: 'Historic immigrant neighborhood now a mix of old tenements and new development.', buildingTypes: 'Pre-war tenements, new luxury high-rises, public housing', transit: 'F (2nd Ave stops), J/M/Z (Essex), B/D (Grand St)', character: 'Gritty history, nightlife, diverse, rapidly changing', challenges: 'Nightlife noise, changing character, varying building quality' },
  'harlem': { name: 'Harlem', borough: 'Manhattan', description: 'Historic Black cultural capital experiencing renaissance and development.', buildingTypes: 'Brownstones, pre-war apartments, new developments, public housing', transit: '2/3 (Lenox), A/B/C/D (various), 4/5/6 (Lexington)', character: 'Rich cultural history, strong community, improving amenities', challenges: 'Rapid gentrification, varying block-by-block conditions' },
  'washington-heights': { name: 'Washington Heights', borough: 'Manhattan', description: 'Northern Manhattan neighborhood with pre-war charm and diverse community.', buildingTypes: 'Pre-war apartments, some walk-ups, affordable for Manhattan', transit: '1 train (Broadway), A train (Fort Washington)', character: 'Dominican culture, Fort Tryon Park, community-oriented, more affordable', challenges: 'Far from Midtown, some steep hills, fewer dining options' },
  'williamsburg': { name: 'Williamsburg', borough: 'Brooklyn', description: 'Once the epicenter of Brooklyn\'s creative scene, now a mature upscale neighborhood.', buildingTypes: 'Converted warehouses, new luxury towers, older walk-ups', transit: 'L train (multiple stops), G train (at Metropolitan), J/M/Z (south)', character: 'Trendy, excellent food/nightlife, waterfront parks, young professionals', challenges: 'Expensive, L train dependent, crowded on weekends' },
  'bushwick': { name: 'Bushwick', borough: 'Brooklyn', description: 'Artist community with DIY spirit, still rougher edges but rapidly changing.', buildingTypes: 'Walk-ups, converted industrial, some new construction', transit: 'L train (DeKalb to Halsey), J/M/Z (Myrtle-Broadway area)', character: 'Artsy, nightlife, street art, warehouse parties, diverse', challenges: 'Limited transit options, still some safety concerns, changing fast' },
  'park-slope': { name: 'Park Slope', borough: 'Brooklyn', description: 'Family-friendly brownstone neighborhood with excellent Prospect Park access.', buildingTypes: 'Brownstones, limestone row houses, some apartment buildings', transit: 'F/G (7th Ave), R (4th Ave), 2/3 (Grand Army Plaza)', character: 'Family-oriented, stroller capital, great restaurants, progressive', challenges: 'Expensive, competitive for families, parking difficult' },
  'bedford-stuyvesant': { name: 'Bedford-Stuyvesant', borough: 'Brooklyn', description: 'Largest Black community in Brooklyn with beautiful brownstones.', buildingTypes: 'Brownstones, row houses, pre-war apartments', transit: 'A/C (various), G (Bedford-Nostrand), J/M/Z (at Myrtle)', character: 'Strong community, beautiful architecture, changing demographics', challenges: 'Transit limited in some areas, rapid gentrification, varying blocks' },
  'crown-heights': { name: 'Crown Heights', borough: 'Brooklyn', description: 'Diverse neighborhood split between Caribbean and Hasidic communities.', buildingTypes: 'Pre-war apartments, brownstones, some new development', transit: '2/3/4/5 (Eastern Parkway), S shuttle to Franklin Ave', character: 'Culturally rich, near Brooklyn Museum, West Indian Day Parade', challenges: 'Some areas far from subway, block-by-block variation' },
  'dumbo': { name: 'DUMBO', borough: 'Brooklyn', description: 'Small converted-industrial neighborhood with stunning Manhattan views.', buildingTypes: 'Converted warehouses, luxury lofts, new developments', transit: 'F (York St), A/C (High St), NYC Ferry', character: 'Tech companies, waterfront parks, touristy, stunning views', challenges: 'Very expensive, crowded with tourists, limited grocery/services' },
  'greenpoint': { name: 'Greenpoint', borough: 'Brooklyn', description: 'Polish heritage neighborhood with waterfront development and neighborhood feel.', buildingTypes: 'Row houses, walk-ups, new waterfront towers', transit: 'G train (Greenpoint Ave, Nassau Ave), NYC Ferry', character: 'Neighborhood feel, excellent food, quieter than Williamsburg', challenges: 'G train only (unreliable), far from Manhattan, limited nightlife' },
  'sunset-park': { name: 'Sunset Park', borough: 'Brooklyn', description: 'Working-class neighborhood with large Chinese and Latin American communities.', buildingTypes: 'Row houses, walk-ups, some larger apartment buildings', transit: 'D/N/R (4th Ave), multiple stops', character: 'Diverse, excellent food, Industry City, Sunset Park views', challenges: 'Far from Manhattan, some industrial areas, gentrifying' },
  'bay-ridge': { name: 'Bay Ridge', borough: 'Brooklyn', description: 'Residential neighborhood at Brooklyn\'s southwestern tip with waterfront access.', buildingTypes: 'Single-family homes, low-rise apartments, some co-ops', transit: 'R train (multiple stops along 4th Ave)', character: 'Residential, family-friendly, Middle Eastern food, waterfront', challenges: 'Long commute to Manhattan, limited nightlife, car helpful' },
  'astoria': { name: 'Astoria', borough: 'Queens', description: 'Diverse neighborhood known for Greek heritage, excellent food, and relative affordability.', buildingTypes: 'Walk-ups, low-rise apartments, some new developments', transit: 'N/W trains (multiple stops), R/M (Steinway)', character: 'Diverse, great food scene, young professionals, neighborhood feel', challenges: 'N/W elevated (noisy), no express train, crowded bars/restaurants' },
  'long-island-city': { name: 'Long Island City', borough: 'Queens', description: 'Former industrial area transformed into high-rise residential with Manhattan views.', buildingTypes: 'New luxury high-rises, converted warehouses, some older buildings', transit: '7 train, E/M (Court Square), G (Court Square), N/W (Queensboro)', character: 'Modern, convenient, waterfront parks, growing restaurant scene', challenges: 'Somewhat sterile, still developing neighborhood feel, expensive new buildings' },
  'flushing': { name: 'Flushing', borough: 'Queens', description: 'One of the largest Chinatowns outside Asia with exceptional food.', buildingTypes: 'Mixed - apartments, condos, houses, new developments', transit: '7 train terminus, LIRR (Port Washington branch)', character: 'Bustling, incredible food, diverse Asian communities, busy', challenges: 'Far from Manhattan (end of 7), very crowded downtown' },
  'jackson-heights': { name: 'Jackson Heights', borough: 'Queens', description: 'Extremely diverse with large South Asian and Latin American communities.', buildingTypes: 'Garden apartments, co-ops (historic), some newer buildings', transit: 'E/F/M/R (Roosevelt Ave), 7 train (74th St)', character: 'Incredible diversity, amazing food, historic garden apartments', challenges: 'Crowded transit, Roosevelt Ave noise, parking difficult' },
  'forest-hills': { name: 'Forest Hills', borough: 'Queens', description: 'Affluent residential area with excellent schools and neighborhood feel.', buildingTypes: 'Tudor-style houses (Gardens), co-ops, apartments', transit: 'E/F/M/R (71st-Continental)', character: 'Suburban feel, excellent restaurants, quiet residential streets', challenges: 'Expensive for Queens, limited nightlife, express trains skip sometimes' },
  'hells-kitchen': { name: 'Hell\'s Kitchen', borough: 'Manhattan', description: 'Vibrant neighborhood west of Times Square with theater district energy and diverse dining.', buildingTypes: 'Pre-war walk-ups, post-war high-rises, new luxury towers', transit: 'A/C/E (8th Ave), N/Q/R/W/S (Times Sq), 1/2/3 (7th Ave)', character: 'Theater district, diverse dining, energetic, LGBTQ-friendly', challenges: 'Tourist crowds, nightlife noise, Times Square congestion' },
  'downtown-brooklyn': { name: 'Downtown Brooklyn', borough: 'Brooklyn', description: 'Brooklyn\'s civic and commercial center with major transit hub and new residential towers.', buildingTypes: 'New luxury high-rises, converted office buildings, some older apartments', transit: 'Nearly every Brooklyn subway line (2/3/4/5/A/C/F/G/N/Q/R/W)', character: 'Transit hub, growing residential, shopping district, urban core', challenges: 'Construction heavy, can feel sterile, less neighborhood character' },
  'ridgewood': { name: 'Ridgewood', borough: 'Queens', description: 'Working-class neighborhood on Brooklyn border with historic row houses and growing arts scene.', buildingTypes: 'Historic row houses, walk-ups, limestone buildings', transit: 'M train (multiple stops), L train (Halsey)', character: 'Affordable, historic architecture, emerging arts scene, quiet', challenges: 'Limited subway options, far from Manhattan, gentrifying' },
  'sunnyside': { name: 'Sunnyside', borough: 'Queens', description: 'Quiet residential neighborhood known for historic Sunnyside Gardens development.', buildingTypes: 'Garden apartments, row houses, some newer buildings', transit: '7 train (multiple stops), LIRR', character: 'Quiet, family-friendly, historic gardens, Irish heritage', challenges: 'Limited nightlife, fewer dining options, mostly residential' },
  'fordham': { name: 'Fordham', borough: 'Bronx', description: 'Busy commercial corridor anchored by Fordham University and Fordham Road shopping.', buildingTypes: 'Pre-war apartments, walk-ups, some newer developments', transit: 'B/D trains (Fordham Rd), 4 train (Fordham Rd), Metro-North', character: 'Commercial hub, university area, diverse, busy shopping district', challenges: 'Busy and crowded, noise from Fordham Road, varying building quality' },
  'kingsbridge': { name: 'Kingsbridge', borough: 'Bronx', description: 'Northwest Bronx neighborhood with mix of residential and commercial areas.', buildingTypes: 'Pre-war apartments, Art Deco buildings, some houses', transit: '1/4 trains, multiple bus routes', character: 'Diverse, residential pockets, improving amenities, community-oriented', challenges: 'Some areas far from subway, varying conditions by block' },
  'riverdale': { name: 'Riverdale', borough: 'Bronx', description: 'Affluent, leafy neighborhood that feels more suburban than typical NYC.', buildingTypes: 'Single-family homes, luxury co-ops, estates', transit: '1 train (limited stops), express buses, Metro-North', character: 'Suburban feel, excellent schools, green spaces, wealthy', challenges: 'Far from Manhattan, limited subway, car often necessary' },
  'mott-haven': { name: 'Mott Haven', borough: 'Bronx', description: 'Rapidly changing South Bronx neighborhood with growing arts community and new development.', buildingTypes: 'Pre-war walk-ups, new developments, converted industrial', transit: '6 train (multiple stops), 2/5 (3rd Ave-149th)', character: 'Arts district, rapidly gentrifying, affordable (for now), waterfront access', challenges: 'Still rough in areas, safety concerns, rapid change displacing residents' },
  'pelham-bay': { name: 'Pelham Bay', borough: 'Bronx', description: 'Northeast Bronx neighborhood near NYC\'s largest park with suburban character.', buildingTypes: 'Co-ops, houses, garden apartments, smaller buildings', transit: '6 train (Pelham Bay Park terminus)', character: 'Residential, quiet, near Pelham Bay Park, Italian-American heritage', challenges: 'Far from Manhattan (end of 6 train), limited amenities, car helpful' },
  'st-george': { name: 'St. George', borough: 'Staten Island', description: 'Staten Island\'s downtown and ferry terminal area with waterfront development.', buildingTypes: 'Mixed - apartments, condos, some historic buildings', transit: 'Staten Island Ferry (free to Manhattan), S40/S44/S46 buses', character: 'Ferry terminal hub, government center, waterfront views, improving', challenges: 'Ferry-dependent for Manhattan, limited subway, still developing' },
  'stapleton': { name: 'Stapleton', borough: 'Staten Island', description: 'Historic Staten Island neighborhood with Victorian homes and waterfront access.', buildingTypes: 'Victorian houses, row houses, some apartments', transit: 'Staten Island Ferry, S51/S76/S78 buses', character: 'Historic, diverse, waterfront, community-oriented, improving', challenges: 'Ferry-dependent, limited dining/nightlife, gentrifying slowly' }
}
